export default {
    'x_1': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAJBAMAAAAfoWtkAAAALVBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAOrOgAAAADnRSTlMAZlSrMol2zZkiu+8QRFoMR9cAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABCSURBVAgdY2AQMhFNYAACRoZwjgSeBQwMnAzLGBjUNoDEngAxiMGygecAiHGdo4ARLHJZJFAGIgVSBlYDoq8+cwAAEQYOIHl79ggAAAAASUVORK5CYII=',
        width: 15,
        height: 9,
    },
    'x_2': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAJBAMAAAAfoWtkAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAZlSrMol2zZkiu+8QRN0yjQrUAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAT0lEQVQIHWNgEDIRTWAAAkaGcI6Ea8kHGDgZljHwBLAaAMW+MHA+YCpgYGDZwHPgAHMAw3WOAkYGhstAJBIow8DSAFQCAm4MCWCaZ///BgCJMxCCs1DRDAAAAABJRU5ErkJggg==',
        width: 15,
        height: 9,
    },
    '\\tilde x_1': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAOBAMAAAACpFvcAAAALVBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAOrOgAAAADnRSTlMAibtEEGYimVSrMnbN7/N5b2kAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABNSURBVAgdY2BgVHZlAAOzdBUIAw8ZMStwA0ialUGGfQOLAgMDG4M2A0P3BZDYKyAGMbgusDiAGDbsB1jBIpZRoiEQKZAysBoQbfh6AQDKAQ9+7NAdxgAAAABJRU5ErkJggg==',
        width: 15,
        height: 14,
    },
    '\\tilde x_2': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAOBAMAAAACpFvcAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAibtEEGYimVSrMnbN790e/eF3AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAW0lEQVQIHWNgYFR2ZQADs3QVCAMPGTErcANImpVBhn2D9U4HBjYGbQYWAcYJQLFfDGwPOA4wMHBdYHFw4BRgsGE/wMrAYAlEUaIhDFwFIH1AsJoBbAIDy/3/BQDxFhCDjtVbQAAAAABJRU5ErkJggg==',
        width: 15,
        height: 14,
    },
    '\\hat x_1': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPBAMAAADJ+Ih5AAAALVBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAOrOgAAAADnRSTlMAEJm7iTIiZlSrds3vRDVNKzMAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABTSURBVAgdY2BgYGSAAmUBCIMlUAHCYEPIQZXAqYqpJQtAHHYGb6YFjAYMDGwMVgwMXQdAYk+BGMRgPcAoAGLcZtrADha5WepeCJECyiIYV14FAADEIBCkRUFG6AAAAABJRU5ErkJggg==',
        width: 15,
        height: 15,
    },
    '\\hat x_2': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPBAMAAADJ+Ih5AAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAEJm7iTIiZlSrds3vRN2VhW3ZAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAYklEQVQIHWNgYGBkgAJlAQiDJVABwmBDyEGVwKmKqSULQBx2Bm+mBbdWCjCwMVgxMDqwTACKfWVge8CxgYGB9QCjgACnA8Ntpg3sDAw3gajUvZCBVQGkDwiiGBaAacbz/xUAGgMRsd6e95cAAAAASUVORK5CYII=',
        width: 15,
        height: 15,
    },
    '\\tilde x_1 \\rightarrow \\hat x_1': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAPBAMAAABHIsEFAAAALVBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAOrOgAAAADnRSTlMAibtEEGYimVSrMnbN7/N5b2kAAAAJcEhZcwAADsQAAA7EAZUrDhsAAADISURBVBgZY2DAARwg4ozKrlgUsKtABM3SoQwUNVLuKFw0TgKDA5oImMuMVRSmkksAxgLTEbMCNyALTAFxWDuXSoNpBhn2DSwKICYEeCYA6QDGA9UMTgwMbAzaDAzdF0AynDNBYM4LIDOBaQMDx16Q4CsgBsuCOEA1ASCSbwEDAy+Q5rrA4oAsKwWSZFjL4AKStWE/wIqsl6UAKMd8oIYhACRrGSUagizLvQAkO3VhqAPYZCAHWRbMhRAge0HA8PUCMI1CMMvtAgDMAyOrE1RQMwAAAABJRU5ErkJggg==',
        width: 58,
        height: 15,
    },
    '\\tilde x_2 \\rightarrow \\hat x_2': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAPBAMAAABHIsEFAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAibtEEGYimVSrMnbN790e/eF3AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAA4ElEQVQYGWNgwAEcIOKMyq5YFLCrQATN0qEMFDVS7ihcNE4CgwOaCJjLjFUUppJLAMYC0xGzAjcgC0wBcVg7l0qDaQYZ9g3WOx1AbDDwTABSAYwHqpl3T2FgY9BmYBFgnAAU4pwJAnN+AJkJTBsYHBkkgaxfDGwPOA4AGRDAGQCi+Rcw5DH0MDBwXWBxcOBEuEUKrGgtgwsLw0QGG/YDrAwMlhB9QJKlAEgwH6hhCGBgnsBgGSUawsAFEoIA7gVAmnnqwlAHhuVQodUMG6AsJIprAzeYx3L/P0IzXN73/3cAOuQqGz5nILcAAAAASUVORK5CYII=',
        width: 58,
        height: 15,
    },


    'x': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAAKlBMVEX///9wcHBAQEAQEBCQkJCwsLBQUFCgoKDQ0NDw8PDAwMCAgIDg4OD///8WUFDjAAAAAXRSTlMAQObYZgAAADpJREFUCB1jYDi9YPUEBo6C7JAEBm6GbdwFDDwMKQwgYAEiOAx4DjAEcyuwMDCElapKMDDwHOBgYAAAOs0JhGzTMMIAAAAASUVORK5CYII=',
        width: 9,
        height: 9,
    },
    '\\tilde x': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAMBAMAAABCcoqQAAAALVBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAOrOgAAAADnRSTlMAibtEEGYimVSrMnbN7/N5b2kAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAA5SURBVAgdY2BgVHZlYGAwS1cBkpggYlbgBgZWBhn2DQxsDNpg+VcgkusCiwODDfsBVgYGyyjREAYA5ugIM1x3AzMAAAAASUVORK5CYII=',
        width: 9,
        height: 12,
    },
    '\\hat x': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAANBAMAAACJLlk1AAAALVBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAOrOgAAAADnRSTlMAEJm7iTIiZlSrds3vRDVNKzMAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAA/SURBVAgdY2BgYGQAAWUBIMESqAAk2aBCQCYUVEwtWcDAzuDNtAAoaQUWfAoiWQ8wCjDcZtrAzsBws9S9kAEA2kYJW5sQCjcAAAAASUVORK5CYII=',
        width: 9,
        height: 13,
    },
    'p(x)': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAASBAMAAAAnJKpfAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAZolEVJky7xAi3bvNq3YTgoj/AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAxElEQVQYGVWQvQ4BQRRGz+7ajbHxs55gKqWIiEqxjagkKolEBI1GoRKVKCUKHsEjeIR9BAq9Sq1UMtfYMMnMd+Yk92bmgl1NSed7BaWFbRjOi4C7Tahb2qVmYClMzdGSG1tQiYVMD8qNdo3gBE53UsU7EzRWakHmDCU3GREkKF8HTzGH8IYx5GrOQqoojjFV7Ak10nnGFtO5Qws44iVDSrgxXCMN9PEu02iDeeHyvf9+oR5ifDmhAvO1cFZL/EyDz8QK8AIueR71KuXHxQAAAABJRU5ErkJggg==',
        width: 33,
        height: 18,
    },
    'p(\\tilde x)': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAASBAMAAAC+3HPqAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAZolEVJky7xAi3bvNq3YTgoj/AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAxklEQVQYGT2PPw4BURDGf2xW7EpYTrCFWhQaiS1FJXEAkUejsIVKVIJKZyPROYREo3QECr0jKJVm9i1TfH9eZuZ9A2k5JqUgRYGDFRnBHfKXDWVj350Q2scrxbP1bmKZzPuZpW7F6ee7UGt1mzPI9ccNiCi0lt68D0H+NoIYzw0LH/FJ6SVDMfjN3Fz6qRiBCPaUQt03ZQeyr0cHH+c2JED/e1ZDXOM8JtU1mmchvZpXS/J6bxUDBbnJEK9UbBX+Z8uAEQcvvmV8IcBAuFcHAAAAAElFTkSuQmCC',
        width: 30,
        height: 18,
    },
    'p(\\hat x)': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAASBAMAAAC+3HPqAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAZolEVJky7xAi3bvNq3YTgoj/AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAx0lEQVQYGU2PsQ4BURBFz3pZsbsJyxdsoRaF0paikuiJPBoSW6hEJaLSEbWP8An7CRR6n6BUmnlLYpJ3597JzLw74MJYl2KHAmd5lSK50k1wtKNqncIkUFoMqVwL7Z8g0IGvDosyNAty+ekeNDq99hK8wbQFKeXOJlgNIC7lE8gI/KT8Fn2KnjKUQdj2VtJPzQqkcCRKdN+cA8i+Pl1CTD4mdv896gm+NfdZfef8rKVX/WqI3+ClZKggN1iyrZK9wt+9xqrkyQduWCCyRW4yQgAAAABJRU5ErkJggg==',
        width: 30,
        height: 18,
    },
    'g(\\tilde x)': {
        uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB0AAAASBAMAAABV68jpAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAZnZUu4mZMhDdq0Qize8eZ4jeAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAw0lEQVQYGT2QMQrCMBSGv9qalLagIKJjQNRVxMVN9AIVFCehoOjiITp4gB6hm6uLKII3cOgRvIWOpjH4IPnfF35e/gRMXc3u/ACi2HRWINC4uNXpW8MFwuc25Wj5YNWzmlmtDkwTFZbdBJzOSE6gcWoqwhyW7Nwch7VQyAL5YaY5Ygoliwmf0s9bL+33YpmV8+TLT3EThAoSMh6i0On1ff5mfGbPvTVvg8lTS9F5Tem8Q3ogLK+gO1Tgx+bg/15+/1GBL2cEISUDReXmAAAAAElFTkSuQmCC',
        width: 29,
        height: 18,
    }
}
